### PR TITLE
Version 2.3.0: Disabling Showbox

### PR DESCRIPTION
**Pull request by JorrinKievit**
changes:
Didnt include vidsrc fixes in the changelog because it broke again
- https://github.com/movie-web/providers/pull/145
- https://github.com/movie-web/providers/pull/146
- https://github.com/movie-web/providers/pull/147
- https://github.com/movie-web/providers/pull/148
- https://github.com/movie-web/providers/pull/149
- https://github.com/movie-web/providers/pull/150
- https://github.com/movie-web/providers/pull/151

### CODE REVIEW

**Comment by ztpn** [comment]
Can you also reduce the rank of primewire?

**Comment by zisra** [comment]
@ztpn why is that? Maybe we can fix whatever issue you're having

**Comment by ztpn** [comment]
> @ztpn why is that? Maybe we can fix whatever issue you're having

It's embeds take forever to scrape and it mostly has 360p/480p, sometimes 720p
Many people on discord have been complaining about getting stuck on primewire
Streamvid specifically

**Comment by JorrinKievit** [comment]
> > @ztpn why is that? Maybe we can fix whatever issue you're having
> 
> It's embeds take forever to scrape and it mostly has 360p/480p, sometimes 720p Many people on discord have been complaining about getting stuck on primewire Streamvid specifically

Gonna need to implement a timeout client side

**Comment by ztpn** [comment]
> > > > @ztpn why is that? Maybe we can fix whatever issue you're having
> > > 
> > > 
> > > It's embeds take forever to scrape and it mostly has 360p/480p, sometimes 720p Many people on discord have been complaining about getting stuck on primewire Streamvid specifically
> > 
> > 
> > Gonna need to implement a timeout client side
> 
> It's not broken, it works, just the requests each take like 40 seconds to complete, on top that it also goes to check the stream, make it even slower

**Comment by zisra** [comment]
It doesn't take that long with the extension, works fine for me in fact

**Review by binaryoverload — APPROVED** [review]

**Pull request merged**
