### PR TITLE
filter out duplicate embeds

### PR DESCRIPTION
**Pull request by JorrinKievit**
Multiple embeds of the same site do not really make much sense, because the quality and speed in most cases is the same. We should filter them out to avoid confusion.

From
image

To
image

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [x] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

### CODE REVIEW

**Comment by amamadman** [comment]
There are 4 voe.sx previously, after the change  it is showing one so when it is selected will it try all four links or only the first link

**Comment by JorrinKievit** [comment]
> There are 4 voe.sx previously, after the change it is showing one so when it is selected will it try all four links or only the first link

Only the first link

**Comment by ztpn** [comment]
I don't think it makes sense to change the backend for the UI. You didn't consider the case where the first link is broken while the second isn't, the video in the first link could have been deleted. 
So I'd suggest to not change the providers package and instead filter the embeds in the web app.
You could also do is when there are duplicate embeds show them as one, if the first embed fails try the second duplicate embed something similar to runAlll.

**Comment by JorrinKievit** [comment]
> I don't think it makes sense to change the backend for the UI. You didn't consider the case where the first link is broken while the second isn't, the video in the first link could have been deleted. So I'd suggest to not change the providers package and instead filter the embeds in the web app. You could also do is when there are duplicate embeds show them as one, if the first embed fails try the second duplicate embed something similar to runAlll.

I could agree to this to a certain extend. But a broken link should never be returned by the providers in the first place. If the embed regularly has broken links, it should be checked and not return the stream

**Comment by ztpn** [comment]
> > I don't think it makes sense to change the backend for the UI. You didn't consider the case where the first link is broken while the second isn't, the video in the first link could have been deleted. So I'd suggest to not change the providers package and instead filter the embeds in the web app. You could also do is when there are duplicate embeds show them as one, if the first embed fails try the second duplicate embed something similar to runAlll.
> 
> I could agree to this to a certain extend. But a broken link should never be returned by the providers in the first place. If the embed regularly has broken links, it should be checked and not return the stream

By a broken links I meant deleted links, not broken streams. And it won't return a broken stream, will just return an error. Also, a source shouldn't check if the embeds work or not, it does not make sense.

**Pull request closed without merging**
